version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: morteza
      POSTGRES_PASSWORD: love
      POSTGRES_DB: chat
    # it: has to be port 5432 of container
    ports:
      - "5434:5432"
    networks:
      - app-network
    # for persist the data
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
  server:
    build:
      # where Dockerfile is
      context: ./server
      dockerfile: Dockerfile
    # image name
    image: chat-node-server
    # container name
    container_name: chat-node

    #command: /usr/src/app/node_modules/.bin/nodemon server.js
    # this runs when we run the container
    #command: sh -c "npm run migrate && npm run start"
    command: sh -c "DATABASE_URL='postgresql://morteza:love@postgres:5432/chat?schema=public' npm run migrate && npm run start"
    volumes:
      # match localDir to serverDir =: in terms of changes
      - ./server/:/usr/src/app
      # don't move node_modules
      - /usr/src/app/node_modules
    # map: local:container port
    ports:
      - "3001:3001"
    # dependency containers: (must run first)
    depends_on:
      - postgres
    # pass to .env file
    env_file: ./server/.env
    environment:
      - NODE_ENV=production
      # DO NOT USE : quotation mark !!!!!
      - DATABASE_URL=postgresql://morteza:love@postgres:5432/chat?schema=public
      - JWT_SECRET=e9gol328jw29n2gggbr9cin4
      - CLIENT_URL_DEV=http://localhost:3002
      - CLIENT_URL_PRO=http://localhost:3002
      - CLIENT_VPS_URL=http://51.222.209.98:3002
      - NODE_PORT=3001
      - EMAIL_PASSWORD=zyps sqal ytto prog
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: chat-client
    container_name: chat-react-client
    command: npm run dev
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3002:3002"
    environment:
      - VITE_NODE_ENV=production
      - VITE_API_URL=http://localhost:3001/
      - VITE_API_URL_PRO=http://51.222.209.98:3001/
      - VITE_CLIENT_URL_PRO=http://51.222.209.98:3002
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  postgres_data:
  web-root:
    driver: local